### ISSUE TITLE
Remove IDs from file names of TEI files

### ISSUE THREAD

**Issue by cmil** [dracor-org/czedracor#3]
To be consistent with DraCor naming conventions we should remove the ID part (e.g. `cze000001-`) from the TEI file names. Otherwise the IDs would also appear in API URLs where they usually don't which may be confusing.

**Comment by DanilSko** [comment]
Ok this is fixed here: https://github.com/dracor-org/czedracor/commit/1e1c9ebb7ed5e957d10bbba5bdd8305e9ea83959 I also fixed the remaining validation issues here https://github.com/dracor-org/czedracor/commit/e7595849d47c5d426d95d6af3f59542f2982e8b0, so now it validates Shall we maybe get the CzeDraCor running?
